# Generated by Django 3.2.25 on 2024-06-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=70)),
                ('Fecha_Nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Cargo', models.CharField(choices=[(1, 'Vendedor'), (2, 'Encargado de tienda'), (3, 'Gerente Zona')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IngresoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=50)),
                ('Nombre_encargado', models.CharField(max_length=50)),
            ],
        ),
    ]
