# Generated by Django 3.2.25 on 2024-07-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20240703_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Cargo',
            field=models.CharField(choices=[('Vendedor', 'Vendedor'), ('Encargado de tienda', 'Encargado de tienda'), ('Gerente Zona', 'Gerente Zona')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ingresoventa',
            name='Precio',
            field=models.CharField(max_length=51),
        ),
    ]
