# Generated by Django 3.2.25 on 2024-07-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_auto_20240703_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoventa',
            name='Precio',
            field=models.CharField(max_length=50),
        ),
    ]
