# Generated by Django 3.2.25 on 2024-07-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_ingresoventa_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoventa',
            name='Cliente',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
