# Generated by Django 3.2.25 on 2024-07-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_ingresoventa_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresostock',
            name='Nombre_Producto',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
